### ISSUE TITLE
React Native Maps

### ISSUE THREAD

**Issue by MarlonX19** [lucasmontano/openweathermap-reactnative#27]
What API are we going to use in this project exactly?
I wasn't able to find any info on that...

I suggest we use react native maps, if you guys agree with that I have a second question which is how to safely use the GOOGLE_API_KEY in the android manifest file.

**Comment by gu1ma** [comment]
I think the api used is https://openweathermap.org/api
About the GOOGLE_API_KEY i think we can put it in a enviroment variable or in strings.xml file on android resources, and add the file in .gitignore. About the react native maps, i think it's a good one

**Comment by gu1ma** [comment]
@MarlonX19 
Now that I realized that there is already a discussion about it in this PR
https://github.com/lucasmontano/openweathermap-reactnative/pull/4

**Comment by MarlonX19** [comment]
> @MarlonX19
> Now that I realized that there is already a discussion about it in this PR
> #4

yes, I just read the discussion and it was enought for me to understand how to NOT expose the API_KEY in the android manifesto file.
Just fixed my code as suggested, using local.properties

I'm closing this issue for now.
Thanks.
